version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/python/Dockerfile
      args:
        BASE_IMAGE: ishocon1-app-base:latest
        # ローカルで base image をビルドしない場合は以下を利用すること
        # BASE_IMAGE: showwin/ishocon1_app_base:latest
    image: ishocon1-app-python:latest
    environment:
      ISHOCON_APP_LANG: "${ISHOCON_APP_LANG-python}"
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/ishocon-app"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 120s
    command: [/home/ishocon/run.sh]
    tty: true
    ports:
      - "80:80"
      - "3306:3306"
