ENV["ISHOCON1_DB_USER"]||=""
ENV["ISHOCON1_DB_PASSWORD"]||=""
if ENV["ISHOCON1_DB_PASSWORD"]!=""
	ENV["ISHOCON1_DB_PASSWORD"]=":"+ENV["ISHOCON1_DB_PASSWORD"]
end
Database = DB.open "mysql://#{ENV["ISHOCON1_DB_USER"]}#{ENV["ISHOCON1_DB_PASSWORD"]}@localhost/ishocon1"
